[package]
name = "starter"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm-core = "0.9"
risc0-zkvm-host = "0.9"
risc0-zkvm-serde = "0.9"
serde = "1.0"
sparse-merkle-tree = "0.5.3"
blake2b-ref = { version = "0.3.0", default-features = false}
